/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRegistrationIndexRouteImport } from './routes/_auth/registration/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthBusinessRegistrationIndexRouteImport } from './routes/_auth/business-registration/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppOrdersNewOrdersRouteRouteImport } from './routes/_app/orders/new-orders/route'

const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistrationIndexRoute = AuthRegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBusinessRegistrationIndexRoute =
  AuthBusinessRegistrationIndexRouteImport.update({
    id: '/business-registration/',
    path: '/business-registration/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersNewOrdersRouteRoute = AppOrdersNewOrdersRouteRouteImport.update({
  id: '/orders/new-orders',
  path: '/orders/new-orders',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/demo': typeof DemoRouteRoute
  '/orders/new-orders': typeof AppOrdersNewOrdersRouteRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/business-registration': typeof AuthBusinessRegistrationIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/registration': typeof AuthRegistrationIndexRoute
}
export interface FileRoutesByTo {
  '/demo': typeof DemoRouteRoute
  '/orders/new-orders': typeof AppOrdersNewOrdersRouteRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/business-registration': typeof AuthBusinessRegistrationIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/registration': typeof AuthRegistrationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/demo': typeof DemoRouteRoute
  '/_app/orders/new-orders': typeof AppOrdersNewOrdersRouteRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_auth/business-registration/': typeof AuthBusinessRegistrationIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/registration/': typeof AuthRegistrationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demo'
    | '/orders/new-orders'
    | '/dashboard'
    | '/business-registration'
    | '/login'
    | '/registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo'
    | '/orders/new-orders'
    | '/dashboard'
    | '/business-registration'
    | '/login'
    | '/registration'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/demo'
    | '/_app/orders/new-orders'
    | '/_app/dashboard/'
    | '/_auth/business-registration/'
    | '/_auth/login/'
    | '/_auth/registration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/registration/': {
      id: '/_auth/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthRegistrationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/business-registration/': {
      id: '/_auth/business-registration/'
      path: '/business-registration'
      fullPath: '/business-registration'
      preLoaderRoute: typeof AuthBusinessRegistrationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/new-orders': {
      id: '/_app/orders/new-orders'
      path: '/orders/new-orders'
      fullPath: '/orders/new-orders'
      preLoaderRoute: typeof AppOrdersNewOrdersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppOrdersNewOrdersRouteRoute: typeof AppOrdersNewOrdersRouteRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrdersNewOrdersRouteRoute: AppOrdersNewOrdersRouteRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthBusinessRegistrationIndexRoute: typeof AuthBusinessRegistrationIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegistrationIndexRoute: typeof AuthRegistrationIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthBusinessRegistrationIndexRoute: AuthBusinessRegistrationIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegistrationIndexRoute: AuthRegistrationIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
